### ISSUE TITLE
Item:Gravestone

### ISSUE THREAD

**Issue by Kaelthalon** [TwitchtvCarbs/The-Collection-Issues#11]
The craftable Gravestone from Gravestone seems to be broken. I can place it in the world, but it does nothing. When I hold right-click, my guy 'grabs' at it repeatedly, but nothing happens. When I try to break it, it 'respawns' back in. I have a grave in my back yard and I can't get rid of it :(

Edit 1: I noticed I've placed 3 bug reports tonight... I broke it again!

**Comment by TwitchtvCarbs** [comment]
This seems to be working in the latest version! You can place and break the gravestone and it will spawn a ghost player after breaking.
