### ISSUE TITLE
Extra Utilities Drums are broken

### ISSUE THREAD

**Issue by Kaelthalon** [TwitchtvCarbs/The-Collection-Issues#12]
ExtraUtils' Drums do not actually hold liquids. It's easier if I just showed you what I did.

https://gyazo.com/15903c6ac84de6276b9eaa18207cbe36

Note, I also tried on a regular drum.

**Comment by TwitchtvCarbs** [comment]
This bug has been fixed in the latest update of EU2. When pack updates this will no longer be an issue!
