### ISSUE TITLE
Bug tracker link in game isn't working

### ISSUE THREAD

**Issue by jenfinite** [TwitchtvCarbs/The-Collection-Issues#18]
Reporting a bug in game goes to the below link when hitting the 'open in browser' option:

https://minecraft.curseforge.com/projects/mputils/issues

Copying to clipboard does work, though!

**Comment by TwitchtvCarbs** [comment]
This bug has been reported to the mod author. 

https://github.com/GenDeathrow/MPUtils/issues/11

**Comment by TwitchtvCarbs** [comment]
This was fixed :D HYPE
