### ISSUE TITLE
Render Crash - Random

### ISSUE THREAD

**Issue by Kaelthalon** [TwitchtvCarbs/The-Collection-Issues#23]
Random Crash when I hovered over Base Essence Ingot while in the Refined Storage's GUI. It happened twice, second time being on the T3 Tool Core.

https://pastebin.com/4ifvQAHw

**Comment by Kaelthalon** [comment]
Nvm, I think I found the problem... I found the "0" in my list and it's breaking it =(

**Comment by TwitchtvCarbs** [comment]
Dupe of #14 This bug gets fixed in the latest version of RS. To get rid of the 0 item break your external storage then place again!
