### ISSUE TITLE
Lectern Dupe bug

### ISSUE THREAD

**Issue by Kaelthalon** [TwitchtvCarbs/The-Collection-Issues#7]
If you craft and place a Lectern from Roots, then right click on it with an empty hand, a new lectern will appear on the lectern. Right click to remove it and boom! It's not really that great of a bug, but it's still a bug.

**Comment by TwitchtvCarbs** [comment]
This problem will be solved in the upcoming for the pack. It has been solved already and updated!

https://minecraft.curseforge.com/projects/roots/files/2393068
